module.exports = {
	PROJECT_ADDED: 'Project added successfully.',
	PROJECT_EXIST: 'Project Detail Already Exist',
	PROJECT_DELETED: 'Project deleted successfully',
	PROJECT_UPDATED: 'Project updated successfully',
	DOMAIN_EXIST: 'Domain Detail Already Exist',
	INVALID_DETAILS: 'Given details are invalid',
	INVALID_PROJECT_DETAILS: 'Given project details not found',
	ID_NOT_FOUND: 'Given ID not found',
	PROJECT_DETAIL: 'Project fetched successfully',
	DB_ERROR: 'Database query error.',
	ISSUE_ADDED: 'Issue added successfully',
	ISSUE_DELETED: 'Issue deleted successfully',
	FOLDER_CREATED: 'Folder created successfully',
	FOLDER_UPDATED: 'Folder updated successfully',
	FOLDER_DELETED: 'Folder deleted successfully',
	TESTCASE_ADDED: 'Testcase added successfully',
	TESTCASES_LIST: 'Testcase list fetched successfully',
	TESTCASE_INACTIVE: 'Testcases deleted successfully',
	OWNER_LIST: 'Owner list fetched successfully',
	TESTCASE_UPDATE: 'Testcases updated successfully',
	TESTPLAN_ADDED: 'Testplan added successfully',
	TESTPLAN_INACTIVE: 'Testplan inactivated successfully',
	TESTPLAN_LIST: 'Testplan list fetched successfully',
	TESTPLAN_DETAIL: 'Testplan detail fetched successfully',
	TESTPLAN_UPDATE: 'Testplan updated successfully',
	ACCESS_UPDATED: 'Access updated successfully',
	TESTCYCLE_INACTIVE: 'Testcycle deleted successfully',
	TESTCYCLE_UPDATE: 'Testcycle updated successfully',
	USER_ACCESS_FETCHED: 'Access fetched successfully',
	INSUFFICIENT_ACCESS: 'Access not allowed',
	TESTEXECUTION_CREATED: 'Test Execution created',
	TESTEXECUTION_UPDATED: 'Test Execution updated',
	TESTEXECUTION_LIST: 'Test Execution List Fetched',
	ROLE_ADDED: 'Role added successfully',
	ROLE_UPDATED: 'Role updated successfully',
	ROLE_INACTIVATED: 'Role inactivated successfully',
	ROLE_LIST_FETCHED: 'Role List fetched successfully',
	ROLE_DETAIL: 'Role fetched successfully',
	ROLE_NOT_FOUND: 'Role not found',
	GROUP_ADDED: 'Group added successfully',
	GROUP_INACTIVATED: 'Group inactivated successfully',
	GROUP_LIST_FETCHED: 'Group list fetched successfully',
	GROUP_NOT_FOUND: 'Group not found',
	ROLE_LIST_WITH_USER_FETCHED: 'Role List with users fetched',
	GROUP_LIST_WITH_USER_FETCHED: 'Group List with users fetched',
	USER_ROLE_DELETED: 'User Role deleted successfully',
	GROUP_ROLE_UPDATED:'Group Role Updated Successfully',
	GROUP_UPDATED:'Group Updated Successfully',
	GROUP_DELETED:'Group Deleted Successfully',
	GROUP_DETAIL: 'Group fetched successfully',
	USER_ADDED_TO_GROUP:'User added to group successfully',
	USER_GROUP_DELETED:'User Group deleted successfully',
	ACTIVE_LIST_FETCHED:'All active list fetched sucessfully',
	ALL_LIST_FETCHED:'All list fetched successfully',
	DATA_UPDATED:'Data updated successfully',
	DATA_ADDED:'Data added successfully',
	DATA_DELETED:'Data Deleted Successfully',
	NO_DATA_AVAILABLE:'No Records found',
	USER_ADDED_TO_MODEL: 'User added to model successfully',
	USER_EXIST: 'User already exist',
	ENV_ADDED:'Environment config added successfully',
	ENV_DETAIL:'Environment fetched successfully',
	ENV_LIST_FETCHED:'Environment list fetched successfully',
	LABEL_ADDED:'Label config added successfully',
	LABEL_DETAIL:'Label fetched successfully',
	LABEL_LIST_FETCHED:'Label list fetched successfully',
	COMPONENT_ADDED:'Component config added successfully',
	COMPONENT_DETAIL:'Component fetched successfully',
	COMPONENT_LIST_FETCHED:'Component list fetched successfully',
	COMPONENT_DELETED:'Component deleted successfully',
	COMPONENT_UPDATED:'Component updated successfully',
	DATASET_ADDED:'Dataset config added successfully',
	DATASET_DETAIL:'Dataset fetched successfully',
	DATASET_LIST_FETCHED:'Dataset list fetched successfully',
	STATUS_ADDED: 'Status added successfully',
	STATUS_LIST: 'Configuration status list fetched successfully',
	STATUS_UPDATED:'Configuration status Updated Successfully',
	FIELD_TYPE_DETAIL:'Field type fetched successfully',
	FIELD_TYPE_LIST_FETCHED:'Field type list fetched successfully',
	DATA_FETCHED: 'Data fetched successfully',
	FOLDER_ADDED: 'Folder added successfully',
	FOLDER_LIST:'Folder list fetched successfully',
	TEST_CYCLE_ADDED:'Test cycle added successfully',
	TESTCASE_DETAIL: 'Test case detail fetched successfully',
	TESTCASE_LOCKED: 'This version is already locked',
	VERSION_LIST:'Version list fetched successfully',
	TESTCASE_HISTORY:'Testcase history fetched successfully',
	TESTCASE_VERSION_HISTORY:'Testcase version details fetched successfully',
	TEST_FLAG:'Test flag fetched successfully',
	CLONE_ADD:'Clone addded successfully.',
	FOLDER_NOT_DELETE:'Folder can not be delete',
	EMPTY_FILE:'File is empty. Please add data in it.',
	FILE_FORMAT:'Please upload a valid CSV or xlsx file.',
	COLUMN_MISSING:'The columns in your csv file are not valid/missing. Please refer sample csv file.',
	download_error: 'Error in downloading data.', 
	IMAGE_MISSING: 'Image is missing.',
	IMAGE_UPLOAD_ERROR: 'Image upload error.',
	signed_error: 'Signed image URL error.',
	GLOBAL_ENV_ADDED:'Global Env config added successfully',
	GLOBAL_ENV_DETAIL:'Global Env fetched successfully',
	GLOBAL_ENV_LIST_FETCHED:'Global Env list fetched successfully',
	GLOBAL_ENV_DELETED:'Global Env deleted successfully',
	GLOBAL_ENV_UPDATED:'Global Env updated successfully',
	TESTCYCLE_LIST: 'Test cycle list fetched successfully',
	TESTCASE_LIST:'Test case list fetched successfully',
	TEST_EXECUTED: 'Test case executed successfully',
	NO_TESTCASE: 'Test case list is empty',
	TESTER_LIST: 'Testers list fetched successfully',
	NAME_EXIST: 'Name already exist with this domain,please enter other name',
	ROLE_EXIST: 'Role already exist with this domain, please enter different Role',
	GROUP_EXIST: 'Group already exist with this domain, please enter different group',
	ROLE_EXIST_IN_PROJECT: 'Role already exist with this project, please enter different role',
	GROUP_EXIST_IN_PROJECT: 'Group already exist with this project, please enter different group',
	CF_EXIST: 'Custom field name and field type already exist with this domain, please enter different name or field type.',
	CF_EXIST_WITH_PROJECT: 'Custom field name and field type already exist with this project, please enter different name or field type.',
	NAME_EXIST_WITH_PROJECT: 'Name already exist with this project,please enter other name',
	ISSUES_DETAIL: 'Issues fetched successfully',
	TESTCASE_EXECUTION_LIST:'Testcase execution list fetched successfully',
	DATE_FORMAT_ISSUE:'Some of the details were missed or incorrect from this file. Please edit the imported data and choose or enter the correct details for the respective fields.',
	REPORT_DETAIL: 'Report detail fetched successfully',
	CUSTOM_FILTER_ADD: 'Custom filter added successfully',
	FILTER_LIST: 'Custom filter list fetched successfully',
	FILTER_DELETE: 'Custom filter deleted successfully',
}
